### ISSUE TITLE
pytest installation is broken

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab#131]
As of ` 20.10.0b0` the installation of `pytest` is broken. Trying to execute `pytest` (even without *any* arguments) leads to the following traceback:
```
$ pytest -v
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 689, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named 'pytest_tornasync'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aiida/.local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 136, in main
    config = _prepareconfig(args, plugins)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 314, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/opt/conda/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/helpconfig.py", line 99, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 932, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1204, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1097, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 300, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 431, in register
    self.consider_module(plugin)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 656, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 663, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 693, in import_plugin
    ).with_traceback(e.__traceback__) from e
  File "/opt/conda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 689, in import_plugin
    __import__(importspec)
ImportError: Error importing plugin "pytest_tornasync": No module named 'pytest_tornasync'
```

**Comment by yakutovicha** [comment]
Adress when the https://github.com/CasperWA/voila-optimade-client/issues/183 issue is fixed.
