### ISSUE TITLE
CLI: `aiidalab search` fails with `TypeError`

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab#262]
When a search doesn't produce any results, the `aiidalab search` command fails with a `TypeError`:

```console
$ aiidalab search quantum
Collecting apps and releases... Done.

Traceback (most recent call last):
  File "/opt/conda/bin/aiidalab", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/__main__.py", line 143, in search
    app_requirement.specifier, prereleases
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/app.py", line 226, in find_matching_releases
    specifier.filter(self.releases, prereleases=prereleases)
  File "/opt/conda/lib/python3.7/site-packages/packaging/specifiers.py", line 778, in filter
    for item in iterable:
TypeError: 'NoneType' object is not iterable
```

This is with `aiidalab` v21.11.1 (inside latest `aiidalab-launch` container):

```console
$ aiidalab --version
AiiDAlab, version 21.11.1
```

Note that it might also be preferable to have the `search` command:

* look for packages that contain the specified string by default instead of having to match it explicitly. I.e. `aiidalab search quantum` would correspond to the current `aiidalab search *quantum*`.
* Only show all versions when the user specifies an option for this, just showing the found package names by default.

**Comment by yakutovicha** [comment]
@csadorf can you please take care of this?

**Comment by csadorf** [comment]
> Note that it might also be preferable to have the `search` command:
> 
> * look for packages that contain the specified string by default instead of having to match it explicitly. I.e. `aiidalab search quantum` would correspond to the current `aiidalab search *quantum*`.

@mbercx  think that's slightly problematic, because as a user you can always add those wildcards, but you can then no longer remove them for (desired) exact matches. The current behavior was modeled after that of `conda search`.

As an alternative suggestion, maybe we add message the proposes to use wildcards when the result is empty?
```console
% aiidalab search optimade
Collecting apps and releases... Done.

No app matched your search query, consider to add wildcard symbols (* ?) for a broader search.
```

> * Only show all versions when the user specifies an option for this, just showing the found package names by default.

Agreed, this has been bugging me for a while as well. The current behavior was – again – modeled after `conda search` which shows all versions. Would knowing this change your opinion on this?

If we implemented this option, would you consider `-a / --all-versions` a good name for it?

**Comment by mbercx** [comment]
> @mbercx think that's slightly problematic, because as a user you can always add those wildcards, but you can then no longer remove them for (desired) exact matches. The current behavior was modeled after that of conda search.

I guess it depends on what you're used to. My suggested behaviour corresponds to `brew search`. ^^ I would argue that the  `brew search` behaviour is better for AiiDAlab, since we are unlikely to have that many packages anytime soon that the user is flooded with search results. Especially when we no longer show all versions by default. `apt search` even goes further and also looks in the description by default.

> As an alternative suggestion, maybe we add message the proposes to use wildcards when the result is empty?

Or, maybe once we have such a large number of packages that the user would need the exact search feature, we add an `--exact` option?

> Agreed, this has been bugging me for a while as well. The current behavior was – again – modeled after conda search which shows all versions. Would knowing this change your opinion on this?

Not really. Once again `brew` has a different behaviour. If the `conda` behaviour was very common across all sorts of package managers, I'd be more inclined to conform to it, but now I think it's better to focus on the best user experience for AiiDAlab.

> If we implemented this option, would you consider -a / --all-versions a good name for it?

Yes, that sounds good! 👍
