### ISSUE TITLE
packaging==22.0 breaks aiidalab install

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#339]
Package `packaging` version 22.0 breaks the `aiidalab install` command. Here's what I see 

```sh
$ aiidalab install aiidalab-widgets-base==2.0.0b0
Collecting apps matching requirements... /
Traceback (most recent call last):
  File "/opt/conda/envs/aiida-base/bin/aiidalab", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/aiidalab/__main__.py", line 399, in install
    install_candidates = {
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/aiidalab/__main__.py", line 400, in <dictcomp>
    requirement: _find_version_to_install(
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/aiidalab/__main__.py", line 297, in _find_version_to_install
    matching_releases = app.find_matching_releases(
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/aiidalab/app.py", line 225, in find_matching_releases
    specifier.filter(self.releases or [], prereleases=prereleases)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/packaging/specifiers.py", line 979, in filter
    parsed_version = _coerce_version(item)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/packaging/specifiers.py", line 25, in _coerce_version
    version = Version(version)
  File "/opt/conda/envs/aiida-base/lib/python3.9/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'stable'
```

Downgrading to version 21.3 fixes the issue. We need to either constrain the version in `setup.cfg` or fix the underlying issue.

Note, in the current docker-stack this is not an issue since `packaging` is already installed in the underlying jupyter image. But as soon as they update we will break.

**Comment by danielhollas** [comment]
Hmm, maybe `packaging` isn't to blame after all. I am playing with conda environments, perhaps I am doing something wrong...

**Comment by yakutovicha** [comment]
Should we switch to flit?

**Comment by danielhollas** [comment]
Haha, I replied via email so didn't see the update, all good. :smile: 

> Nevertheless, I think it makes sense to move aiidalab to flit.

Yep :+1:

**Comment by danielhollas** [comment]
I will re-open this so that we remember to fix this properly (for now we only pinned to the old version of `packaging`).

**Comment by danielhollas** [comment]
I think this the same issue as in https://github.com/aiidalab/aiidalab-registry/issues/103

**Comment by danielhollas** [comment]
The `stable`  version comes from AWB, see https://github.com/aiidalab/aiidalab-registry/issues/103#issuecomment-2186916794
