### ISSUE TITLE
Exception from watchdog dependency

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#340]
I just noticed this exception when running aiidalab-home apps in the notebook, it is hidden in Appmode.

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/app.py", line 530, in check_path_exists_changed
    if self._observer is None or not self._observer.isAlive():
AttributeError: 'InotifyObserver' object has no attribute 'isAlive'
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/app.py", line 530, in check_path_exists_changed
    if self._observer is None or not self._observer.isAlive():
AttributeError: 'InotifyObserver' object has no attribute 'isAlive'
```

This pops-out both in `appstore.ipynb`, `single_app.ipynb` and others.

Might get solve by #328, but will need to test.

**Comment by danielhollas** [comment]
As explained in https://github.com/gorakhargosh/watchdog/pull/837#issue-988964644

> Using `threading.Thread.isAlive` is [deprecated since python 3.8](https://bugs.python.org/issue37804) and was removed in python 3.9. It seems that the codebase uses `is_alive()` internally, only the documentation should be updated.

I'll post a PR shortly.
