### ISSUE TITLE
Error when parsing requirements

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#442]
The App Store crashes on aiidalab/full-stack:edge, with error:

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/conda/lib/python3.9/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected string_end, found '#'  (at char 26), (line:1, col:27)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/utils.py", line 147, in wrapped
    return func(instance, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/app.py", line 931, in refresh
    self._refresh_versions()
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/app.py", line 912, in _refresh_versions
    all_available_versions = list(self._app.available_versions(prereleases=True))
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/app.py", line 184, in available_versions
    version_requirements = [
  File "/opt/conda/lib/python3.9/site-packages/aiidalab/app.py", line 185, in <listcomp>
    Requirement(r)
  File "/opt/conda/lib/python3.9/site-packages/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'# Hotfix'": Expected string_end
```

**Comment by danielhollas** [comment]
I think this is a duplicate of #326
