### ISSUE TITLE
Segfault in pytest for 3.11/3.12

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#446]
So the Python 3.11/3.12 test started failing with a ... Segfault? :scream:

https://github.com/aiidalab/aiidalab/actions/runs/10298925056/job/28505124693

```
Fatal Python error: Segmentation fault

Thread 0x00007fc2fc48f640 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/backends/sqlite.py", line 278 in close
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/backends/base.py", line 116 in close
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/session.py", line 342 in close
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/sessions.py", line 455 in __exit__
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/api.py", line 58 in request
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/api.py", line 73 in get
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 62 in load_app_registry_index
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 138 in is_registered
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 193 in available_versions
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 910 in _refresh_versions
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 924 in refresh
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 148 in wrapped
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/threading.py", line 982 in run
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/threading.py", line 1045 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/threading.py", line 1002 in _bootstrap

Current thread 0x00007fc2ffdc6b80 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/backends/sqlite.py", line 312 in __getitem__
  File "<frozen _collections_abc>", line 774 in get
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/backends/base.py", line 77 in get_response
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/session.py", line 218 in send
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/sessions.py", line 589 in request
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests_cache/session.py", line 183 in request
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/api.py", line 59 in request
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/api.py", line 73 in get
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 62 in load_app_registry_index
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 138 in is_registered
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 323 in find_incompatibilities
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 882 in _is_compatible
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 927 in refresh
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 148 in wrapped
  File "/home/runner/work/aiidalab/aiidalab/tests/test_appclass.py", line 16 in test_init_refresh
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/python.py", line 162 in pytest_pyfunc_call
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/python.py", line 1632 in runtest
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/runner.py", line 173 in pytest_runtest_call
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/runner.py", line 241 in <lambda>
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/runner.py", line 341 in from_call
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/runner.py", line 240 in call_and_report
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/runner.py", line 135 in runtestprotocol
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/runner.py", line 116 in pytest_runtest_protocol
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/main.py", line 364 in pytest_runtestloop
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/main.py", line 339 in _main
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/main.py", line 285 in wrap_session
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/config/__init__.py", line 178 in main
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/config/__init__.py", line 206 in console_main
  File "/opt/hostedtoolcache/Python/3.11.9/x64/bin/pytest", line 8 in <module>
```

**Comment by danielhollas** [comment]
Possibly related to https://github.com/requests-cache/requests-cache/issues/845 / https://github.com/python/cpython/issues/118172, although unlike in those issues, we saw this with Python 3.11 as well.

**Comment by danielhollas** [comment]
Another instance from a job failed last week. It would be nice to find out the first occurence of this

https://github.com/aiidalab/aiidalab/actions/runs/10165272174/job/28112683002?pr=444

**Comment by danielhollas** [comment]
Yet another crash with slightly different stack trace https://github.com/aiidalab/aiidalab/actions/runs/10302477790/job/28516242965?pr=444

```
Thread 0x00007f9cf4663640 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/backends/sqlite.py", line 253 in connection
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/contextlib.py", line 137 in __enter__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/backends/sqlite.py", line 311 in __getitem__
  File "<frozen _collections_abc>", line 807 in get
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/backends/base.py", line 77 in get_response
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/session.py", line 218 in send
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py", line 589 in request
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/session.py", line 183 in request
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py", line 59 in request
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py", line 73 in get
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 65 in load_app_registry_index
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 138 in is_registered
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 335 in find_incompatibilities
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 894 in _is_compatible
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 939 in refresh
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 151 in wrapped
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/threading.py", line 1010 in run
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/threading.py", line 1030 in _bootstrap


Current thread 0x00007f9cf7ebbb80 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/backends/sqlite.py", line 312 in __getitem__
  File "<frozen _collections_abc>", line 807 in get
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/backends/base.py", line 77 in get_response
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/session.py", line 218 in send
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py", line 589 in request
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests_cache/session.py", line 183 in request
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py", line 59 in request
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py", line 73 in get
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 65 in load_app_registry_index
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 138 in is_registered
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 193 in available_versions
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 922 in _refresh_versions
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/app.py", line 936 in refresh
  File "/home/runner/work/aiidalab/aiidalab/aiidalab/utils.py", line 151 in wrapped
  File "/home/runner/work/aiidalab/aiidalab/tests/test_appclass.py", line 16 in test_init_refresh
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/python.py", line 162 in pytest_pyfunc_call
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/python.py", line 1632 in runtest
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/runner.py", line 173 in pytest_runtest_call
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/runner.py", line 241 in <lambda>
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/runner.py", line 341 in from_call
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/runner.py", line 240 in call_and_report
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/runner.py", line 135 in runtestprotocol
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/runner.py", line 116 in pytest_runtest_protocol
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/main.py", line 364 in pytest_runtestloop
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/main.py", line 339 in _main
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/main.py", line 285 in wrap_session
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/config/__init__.py", line 178 in main
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/config/__init__.py", line 206 in console_main
  File "/opt/hostedtoolcache/Python/3.12.4/x64/bin/pytest", line 8 in <module>
```

**Comment by danielhollas** [comment]
I can now reproduce it, seems like this is the reason why AppStore is crashing on the latest image, and looks like the new version of `requests_cache` is indeed the culprit. Here's the stacktrace from running python3.12 under gdb. I'll try to bisect this more before I open an issue upstream.

```
  File "/home/hollas/atmospec/aiidalab-home/segfault.py", line 3, in <module>
    AiidaLabAppStore()
  File "/home/hollas/atmospec/aiidalab-home/home/app_store.py", line 76, in __init__
    AiidaLabApp(app_id, None, None) for app_id in self.index["apps"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/aiidalab/app.py", line 754, in __init__
[Detaching after vfork from child process 865150]
    self._app = _AiidaLabApp.from_id(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/aiidalab/app.py", line 130, in from_id
    remote_registry_entry = load_app_registry_entry(app_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/aiidalab/utils.py", line 70, in load_app_registry_entry
    return requests.get(f"{AIIDALAB_REGISTRY}/apps/{app_id}.json").json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests_cache/session.py", line 183, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests_cache/session.py", line 218, in send
    cached_response = self.cache.get_response(actions.cache_key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests_cache/backends/base.py", line 77, in get_response
    response = self.responses.get(key)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 807, in get
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests_cache/backends/sqlite.py", line 313, in __getitem__
    row = cur.fetchone()
          ^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by danielhollas** [comment]
One more datapoint: Installing requests-cache from main branch, I am not getting a segfault but what looks like a deadlock.

```python
Traceback (most recent call last):
  File "/home/hollas/atmospec/requests-cache/segfault.py", line 3, in <module>
    AiidaLabAppStore()
  File "/home/hollas/atmospec/aiidalab-home/home/app_store.py", line 76, in __init__
    AiidaLabApp(app_id, None, None) for app_id in self.index["apps"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab/aiidalab/app.py", line 748, in __init__
    self._app = _AiidaLabApp.from_id(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab/aiidalab/app.py", line 129, in from_id
    remote_registry_entry = load_app_registry_entry(app_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab/aiidalab/utils.py", line 73, in load_app_registry_entry
    return requests.get(f"{AIIDALAB_REGISTRY}/apps/{app_id}.json").json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/session.py", line 183, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/session.py", line 218, in send
    cached_response = self.cache.get_response(actions.cache_key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/backends/base.py", line 69, in get_response
    response = self.responses.get(key)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 807, in get
  File "/home/hollas/atmospec/requests-cache/requests_cache/backends/sqlite.py", line 314, in __getitem__
    cur.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
^CException ignored in: <module 'threading' from '/usr/lib64/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1613, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**Comment by danielhollas** [comment]
I've identified a concrete commit in `requests_cache` that causes the issue. I'll submit a bug report tomorrow. The easiest way forward for us is to downgrade to v0.9.8. Or alternatively, the problem might go away if we tackle #196

**Comment by danielhollas** [comment]
Interesting new stacktrace with Python 3.12 after converting to CachedSession()

```python
Traceback (most recent call last):
  File "/home/hollas/atmospec/aiidalab/segfault.py", line 3, in <module>
    store = AiidaLabAppStore()
            ^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/home/app_store.py", line 76, in __init__
    AiidaLabApp(app_id, None, None) for app_id in self.index["apps"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab/aiidalab/app.py", line 748, in __init__
    self._app = _AiidaLabApp.from_id(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab/aiidalab/app.py", line 129, in from_id
    remote_registry_entry = load_app_registry_entry(app_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab/aiidalab/utils.py", line 59, in load_app_registry_entry
    return session.get(f"{AIIDALAB_REGISTRY}/apps/{app_id}.json").json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/session.py", line 127, in get
    return self.request('GET', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/session.py", line 183, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiidalab-home/.venv/lib64/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/session.py", line 218, in send
    cached_response = self.cache.get_response(actions.cache_key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/backends/base.py", line 69, in get_response
    response = self.responses.get(key)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 807, in get
  File "/home/hollas/atmospec/requests-cache/requests_cache/backends/sqlite.py", line 318, in __getitem__
    return self.deserialize(key, row[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/backends/base.py", line 353, in deserialize
    obj = self.serializer.loads(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/requests-cache/requests_cache/serializers/pipeline.py", line 61, in loads
    value = step(value)
            ^^^^^^^^^^^
EOFError: Ran out of input
```

**Comment by danielhollas** [comment]
Here's a minimal reproducer that segfaults on both Python 3.9 and 3.12

```python
from threading import Thread

import requests
import requests_cache

requests_cache.install_cache(
    cache_name="segfault_reproducer",
    use_cache_dir=True,  # store cache in ~/.cache/
    backend="sqlite",
    expire_after=60,  # seconds
    old_data_on_error=True,
)

def load_app_registry_index():
    try:
        return requests.get("https://aiidalab.github.io/aiidalab-registry/api/v1/apps_index.json").json()
    except (ValueError, requests.ConnectionError) as error:
        raise RuntimeError("Unable to load registry index") from error

num_threads = 50
threads = []
for _ in range(num_threads):
    t = Thread(target=load_app_registry_index)
    t.start()
    threads.append(t)
```

I also saw a new stacktrace:
```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jovyan/min_segfault.py", line 16, in load_app_registry_index
    return requests.get("https://aiidalab.github.io/aiidalab-registry/api/v1/apps_index.json").json()
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests_cache/session.py", line 159, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests_cache/session.py", line 206, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests_cache/session.py", line 234, in _send_and_cache
    self.cache.save_response(response, actions.cache_key, actions.expires)
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests_cache/backends/base.py", line 91, in save_response
    self.responses[cache_key] = cached_response
  File "/home/jovyan/.local/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 283, in __setitem__
    con.execute(
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 3 supplied.
```
